### ISSUE TITLE
 How much nodes can be managed by efr32 wisun border router

### ISSUE THREAD

**Issue by iot-lorawan** [SiliconLabs/wisun-backhaul-docker#1]
Hi,
     How much nodes can be managed by efr32 wisun border router?
     When the wisun sdk for efr32 will be released,  is there starterkit board will be release?

Best Regards,

**Comment by silabs-JulienT** [comment]
Hi,

The EFR32 border router is provided as a binary demo. It can support several tenth nodes. 
The Wi-SUN SDK is already available in the Gecko SDK 3.2. The Gecko SDK 3.2 can be retrieved using Simplicity Studio 5. The starter kit should be orderable by the end of the week.

Regards,
Julien

**Comment by iot-lorawan** [comment]
Hi Julien，
     Is there recommendatory solution for boaderrouter base efr32fg？
     If the boaderrouter base efr32 can only support tenth nodes， it seem not can  use in production base efr32fg？ the wisun boaderrouter may support up to hundreds nodes base on efr32fg？

Best Regards，

**Comment by silabs-JulienT** [comment]
Hi, 

Silicon Labs plans to introduce an EFR32+Linux host solution able to scale up to the Wi-SUN specification limits. This implementation is scheduled to be released by the end of the year.

Regards,
Julien

**Comment by iot-lorawan** [comment]
Hi Julien,
      It seems similar to the zigbee host ncp's method, it sounds good.
      I looking forward to it.

Best Regards,
