### ISSUE TITLE
Is there sleepy support in  sliconlabs wisun solution

### ISSUE THREAD

**Issue by iot-lorawan** [SiliconLabs/wisun-backhaul-docker#2]
Hi，
      Does the siliconlabs wisun solution support sleepy device？

Best Regards，

**Comment by silabs-JulienT** [comment]
Hi,

Silicon Labs' solution does not currently support sleepy devices. The solution supports the Wi-SUN FAN 1.0 specification. The FAN 1.1 profile will bring official sleepy device support in the specification.
For broad questions not directly related to the repository source code, I recommend using [Silicon Labs community platform](https://community.silabs.com/s/topic/0TO1M000000qHc6WAE/wisun?language=en_US) for your follow-up questions.

Regards,
Julien
